[phases.setup]
nixPkgs = ["nodejs-18_x"]
cmds = ["cp -r voice-assistant-backend/* .", "rm -rf voice-assistant-backend"]

[phases.build]
cmds = ["npm install", "npx prisma generate"]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"